version: "3.9"

services:
  app:
    container_name: django_ecommerce_app
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=ecommerce_db
      - DB_USER=devuser
      - DB_PASSWORD=changeme
      - JWT_SECRET=-0jh#r)(xdhk!!gek-ack)eccvqe9lr*$bej0&*&s2*#_x4q8l
      - JWT_REFRESH_SECRET=&x=dp4m%@^md%0c3kky_u7=@zg8b)x=68ag%_yp$6ml)rq1h2e
      - COOKIES_KEY=^b9dvd0exjq%l3vg+^+&=$asqu46i-+r*a@fdzv269yjw3rgdk
    depends_on:
      - db

  db:
    container_name: postgres-database
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
