# Generated by Django 3.2.21 on 2023-09-16 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230916_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 12, 33, 49, 783035))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
