# Generated by Django 3.2.21 on 2023-09-17 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230917_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 13, 20, 11, 349544)),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
