# Generated by Django 3.2.21 on 2023-09-19 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230917_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('two_factor_auth', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 7, 30, 4, 75237)),
        ),
    ]
