# Generated by Django 3.2.21 on 2023-09-18 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230917_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('token', models.IntegerField()),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2023, 9, 18, 0, 31, 9, 394146))),
            ],
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 0, 30, 8, 972955)),
        ),
    ]
