# Generated by Django 3.2.21 on 2023-09-20 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230920_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauthentication',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 9, 56, 390641)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 11, 7, 55, 948389)),
        ),
    ]
