# Generated by Django 3.2.21 on 2023-09-27 02:07

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230924_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='twofactorauthentication',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 2, 9, 45, 54560)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 21, 7, 44, 649532)),
        ),
    ]
