# Generated by Django 3.2.21 on 2023-09-27 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230927_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='twofactorauthentication',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 2, 40, 28, 516440)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 21, 38, 28, 82012)),
        ),
    ]
