# Generated by Django 3.2.22 on 2023-10-10 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230927_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(help_text='Required', max_length=255, verbose_name='delivery_name')),
                ('delivery_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 to 999.99'}}, help_text='Maximum 999.99', max_digits=5, verbose_name='delivery_price')),
                ('delivery_method', models.CharField(choices=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')], help_text='Required', max_length=255, verbose_name='delivery_method')),
                ('delivery_timeframe', models.CharField(help_text='Required', max_length=255, verbose_name='delivery_timeframe')),
                ('delivery_window', models.CharField(help_text='Required', max_length=255, verbose_name='delivery_window')),
                ('order', models.IntegerField(help_text='Required', verbose_name='list_order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
            },
        ),
        migrations.CreateModel(
            name='PaymentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Selection',
                'verbose_name_plural': 'Payment Selections',
            },
        ),
        migrations.AlterField(
            model_name='twofactorauthentication',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 9, 14, 57, 477546)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 4, 12, 56, 941047)),
        ),
    ]
