# Generated by Django 3.2.22 on 2023-10-10 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20231010_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauthentication',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 9, 16, 11, 655089)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 4, 14, 11, 89763)),
        ),
    ]
